services:
  - type: web
    name: stock-analysis-backend
    runtime: python
    buildCommand: ./build.sh && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: LD_LIBRARY_PATH
        value: /usr/local/lib:/usr/lib
